In [1]:
!pip install gensim

In [2]:
import gensim

In [3]:
from gensim.models import Word2Vec, KeyedVectors

In [4]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

vec_king = wv['king']

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [5]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [7]:
vec_king.shape

(300,)

In [8]:
wv['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [9]:
wv.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [10]:
wv.most_similar('angry')

[('irate', 0.8138925433158875),
 ('enraged', 0.7705066800117493),
 ('indignant', 0.7013434171676636),
 ('incensed', 0.6881307363510132),
 ('annoyed', 0.6847162246704102),
 ('agitated', 0.6821000576019287),
 ('frustrated', 0.6720573306083679),
 ('furious', 0.6702253222465515),
 ('unhappy', 0.6646261811256409),
 ('outraged', 0.6598437428474426)]

In [11]:
wv.similarity("car", "bike")

np.float32(0.5854154)

In [14]:
wv.similarity("apple", "banana")

np.float32(0.5318406)

In [15]:
vec = wv['king'] - wv['man'] + wv['queen']

In [16]:
vec

array([-0.19494629, -0.2446289 , -0.09539795,  0.3461914 ,  0.01635742,
       -0.08374023,  0.23876953, -0.42193604, -0.28955078,  0.41699982,
       -0.3466797 , -0.43359375,  0.01025391,  0.1256485 ,  0.06689453,
       -0.09790039,  0.20507812, -0.10098267,  0.08251953,  0.32373047,
        0.4580078 ,  0.24821472, -0.20288086,  0.28955078,  0.10253906,
       -0.03857422, -0.48242188, -0.1081543 ,  0.15527344, -0.15270996,
       -0.21386719, -0.20581055,  0.10595703,  0.63391113, -0.5810547 ,
       -0.3017578 , -0.11279297,  0.39648438, -0.09619141,  0.03613281,
        0.21411133, -0.6088867 ,  0.3408203 ,  0.12298584,  0.29492188,
       -0.00195312, -0.03781128,  0.16821289,  0.15332031,  0.24481201,
       -0.04626465,  0.13183594, -0.2626953 ,  0.17150879, -0.40771484,
        0.02772522, -0.41064453, -0.1862793 ,  0.07617188, -0.10406494,
        0.14550781,  0.41992188,  0.00299072,  0.2758789 ,  0.18359375,
       -0.39794922, -0.07757568,  0.12207031, -0.43115234,  0.42

In [17]:
wv.most_similar([vec])

[('queen', 0.8422122001647949),
 ('king', 0.8070623278617859),
 ('queens', 0.6293326020240784),
 ('monarch', 0.6233264207839966),
 ('kings', 0.599048376083374),
 ('princess', 0.5685814619064331),
 ('royal', 0.55137038230896),
 ('princes', 0.5398682951927185),
 ('NYC_anglophiles_aflutter', 0.5370354652404785),
 ('Queen_Consort', 0.5246095061302185)]